### ISSUE TITLE
Some badges are missing in certain packs 

### ISSUE THREAD

**Issue by K8Berry** [AntiMach/allbadge-tool#2]
I maybe have done some mistakes while using the app, but I noticed that are some packs with missing badges?
For example, in **Pokemon00** from **USA v131**, the badges file 0004 and 0005 are missing, while in **Pokemon05** from **JPN v131**, the badges 0653 - 0662 are missing.

**Comment by AntiMach** [comment]
Unfortunately, I don't think this is an issue on my part, but rather on Nintendo's part since they don't provide every badge within each region and version. If you want the most amount of badges (i can't even garantee that it's all the badges), you will have to extract the pc.sarc from the Japanese Version of the Nintendo Badge Arcade, update 1.3.1, there's no other way around it.

To do this, you can use either the update installed on your system, or an extracted copy of the update (.cia), followed by using GodMode9 to extract the pc.sarc file. To aid in this process, you can make use of [these GodMode9 scripts](https://github.com/AntiMach/allbadge-tool/releases/tag/gm9script).
